### ISSUE TITLE
Imgur album json errors on Reddit as of 3/30

### ISSUE THREAD

**Issue by heavyboots** [chrisfoley/lightboxe#2]
I noticed suddenly as of yesterday that Imgur seems to be giving errors for albums now.

For example… **http://imgur.com/a/1Sf8n**

returns… **Failed to load //api.imgur.com/2/album/1Sf8n.json**

Presumably they changed something recently?

Absolutely couldn't live without this extension by the way. So amazingly useful!

**Comment by chrisfoley** [comment]
@heavyboots Sure enough, they depreciated their v2 public API. 
I'm going to push an update tonight that uses their newer API.
Thanks for reporting, glad to hear you find it useful!

**Comment by chrisfoley** [comment]
Should be working again with version 3.1.0.

**Comment by chrisfoley** [comment]
Should be working again with version 3.1.0.
